<?php

namespace AppBundle\Repository;

/**
 * CreateSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreateSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
